name: Release
on:
  push:
    branches:
      - master
jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    if: github.repository == 'starship/starship'
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
